### ISSUE TITLE
Error with missing xdg-utils package

### ISSUE THREAD

**Issue by elalitte** [kirklin/vite-boot#1]
**Describe the bug/issue**

I had a problem installing vite-boot on multiple servers and the issue were not that obvious to find.
You need the package xdg-utils in order to be able to serve your project (error arriving when running dev) which is not the case in many non gui environnements like servers.
To correct this you just have to install it with your prefered system package manager :
$ apt install xdg-utils --fix-missing
Hope this helps !

**Comment by kirklin** [comment]
Hello, I saw your question. Based on the information you provided, it sounds like you may have encountered a problem when running either `npx degit` or `pnpm install`. If the problem occurred when running `npx degit`, then it is outside of our scope of support and you can report the issue to [degit](https://github.com/Rich-Harris/degit). If you encountered a problem when running `pnpm install`, please contact us and we will do our best to help you resolve the issue.

**Comment by elalitte** [comment]
All the install passes correctly, it's when I try to start the dev server (npm run dev) that the error occurs.
I just mentionned this error as other people could encountered the same problem.
Installing the package corrects it.  
Thanks for your quick response !
