### ISSUE TITLE
移动端语言设置和主题设置点击空白处不会自动收起下拉框

### ISSUE THREAD

**Issue by ningmeng0503** [kirklin/vite-boot#4]
### Describe the bug

在移动端时，点击语言设置和主题设置后，再点击空白处的时候，不会自动收起

### Reproduction

1

### System Info

```Shell
1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/kirklin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/kirklin/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kirklin** [comment]
非常感谢您报告这个问题。为了更好地帮助解决问题，我们需要进一步了解该问题的详细情况。以下是一些可能有用的信息：

请您提供您使用的移动设备的型号、操作系统、浏览器类型和版本。

请您提供更详细的操作步骤，例如点击语言设置和主题设置后是什么反应，空白处是指页面的哪个区域，点击空白处后是否有其他反应等。

请您提供浏览器控制台的输出或者截图，以便更好地诊断问题。

您可以尝试在其他移动设备上进行测试，看看是否可以复现问题。如果可以，请提供详细的操作步骤和设备信息。

感谢您的理解和配合，我们会尽力帮助您解决问题。如果您需要更多帮助，请随时提问，我们将竭尽全力为您提供支持。
